---
title: "assignment5"
author: "Rachel Green"
date: "November 27, 2018"
output: html_document
---

Setup Code:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(car)
library(userfriendlyscience)
library(knitr)
library(kableExtra)
library(effsize)
library(ggrepel)
library(reshape2)
library(stargazer)
fs = read_csv("faculty_salary_data_2008_2009_survey.csv")
ge = read_csv("grad_enrollment.csv")
ms = read_csv("median_salary_doctoral_recipients.csv")
pf = read_csv("phds_by_field_1985_2015.csv")
```

Problem 1 (Jeremy):
```{r}

total_males <- ge %>% 
  select(year, total_males) %>% 
  mutate(total = total_males) %>% # 
  mutate(sex = rep("male", length(total_males))) %>% 
  select(year, total, sex)
total_females <- ge %>% 
  select(year, total_females) %>% 
  mutate(total = total_females) %>% 
  mutate(sex = rep("female", length(total_females))) %>% 
  select(year, total, sex)
total <- rbind(total_males, total_females)

total_enroll_plot <- ggplot(total, aes(x = year, y = total, shape = sex, color = sex)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm") +
  theme_classic() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.7)) +
  labs(x = "Year", y = "Total Male & Female Graduate Student \nEnrollment in the U.S.") +
  scale_y_continuous() +
  scale_color_manual(values = c("grey11", "gray48")) +
  annotate("text", 
           x = 2010, 
           y = 940000, 
           label = "y = 9.42e-05x + 1.9e03", 
           family = "Times New Roman", 
           size = 3) +
  annotate("text", 
           x = 2010, 
           y = 880000, 
           label = "italic(R)^2 == 0.85", 
           parse = TRUE, 
           family = "Times New Roman", 
           size = 3) +
  annotate("text", 
           x = 1999, 
           y = 1600000, 
           label = "y = 3.26e-05x + 1.96e03", 
           family = "Times New Roman", 
           size = 3) +
  annotate("text", 
           x = 1999, 
           y = 1550000, 
           label = "italic(R)^2 == 0.98", 
           parse = TRUE, 
           family = "Times New Roman", 
           size = 3) 
total_enroll_plot
# Figure 1. Relationship between year and graduate student enrollment for both males and females (1967-2015). Year significantly predicts graduate student enrollment in the U.S. for both males (*b* = 9.42e-05, t(47) = 16.61, *p* <0.001) and females (*b* = 3.26e-05, t(47) = 51.66, *p* < 0.001) with a strong positive correlation between year and both sexes (Pearson's *r* (males) = 0.92, Pearson's *r* (females) =  0.99). The overall models (male enrollment = 9.42e-05(year) + 1.9e03, female enrollment = 3.26e-05(year) + 1.96e03) explain a significant amount of variance in salary for males (F(1,47) = 276, *p* < 0.001), R^2^ = 0.85 and females (F(1.9,47) = 2669, *p* < 0.001, R^2^ = 0.98). Gray region is the 95% confidence interval for the mean predicted values.

# lm for males
enrollment_males_lm <- lm(year ~ total, data = total_males)
summary(enrollment_males_lm)
cor.test(total_males$total, total_males$year) 
# lm for females
enrollment_females_lm <- lm(year ~ total, data = total_females)
summary(enrollment_females_lm)
cor.test(total_females$total, total_females$year) 


m_1967 <- total_males %>% # subset 1967 males
  filter(year == 1967)
m_2015 <- total_males %>% # subset 2015 males
  filter(year == 2015)
net_males <- m_2015$total - m_1967$total # net increase from 1967-2015
fold_males <- m_2015$total/m_1967$total # fold increase from 1967-2015
perc_males <- ((m_2015$total - m_1967$total)/m_1967$total) * 100 # % increase from 1967 - 2015


f_1967 <- total_females %>% # subset 1967 females
  filter(year == 1967)
f_2015 <- total_females %>% # subset 2015 females 
  filter(year == 2015)
net_females <- f_2015$total - f_1967$total # net increase from 1967-2015
fold_females <- f_2015$total/f_1967$total # fold increase from 1967-2015
perc_females <- ((f_2015$total - f_1967$total)/f_1967$total) * 100 # % increase from 1967 - 2015


# since 1967, there has been a dramatic rise in female graduate student enrollment in the U.S. as compared to males
# male enrollment has nearly doubled (1.9 fold), whereas female enrollment has seen a 6.5 fold increase
# net increase in males was 59,0865; net increase in females was 1,453,562

```
Problem 1 (Michael):
```{r}
ge_adddecyear <- ge %>%
  mutate(year1 = year - min(year))

lm_gem1 <- lm(total_males ~ year1, data = ge_adddecyear)
summary(lm_gem1)

lm_gef1 <- lm(total_females ~ year1, data = ge_adddecyear)
summary(lm_gef1)

# predict from model over the same time domain
ge_year <- data.frame(year1 = c(0:48))
ge_year$year <- c(1967:2015)
predict_m <- as.data.frame(predict(lm_gem1, newdata = ge_year, se.fit = TRUE, interval="confidence"))
predict_f <- as.data.frame(predict(lm_gef1, newdata = ge_year, se.fit = TRUE, interval="confidence"))
names(predict_m) <- paste(names(predict_m), "m", sep = "_")
names(predict_f) <- paste(names(predict_f), "f", sep = "_")

ge_fullpred <- cbind(ge_adddecyear, predict_m, predict_f)

#ge_predm <- cbind(ge_year, predict_m)
#ge_predf <- cbind(ge_year, predict_f)

lines <- c("Male"="steelblue3","Female"="tomato3")

ge_plot <- ggplot(ge_fullpred, aes(x = year, y = total_females)) +
  geom_ribbon(aes(ymin = fit.lwr_f, ymax = fit.upr_f), fill = "tomato3", alpha = 0.35) +
  geom_ribbon(aes(ymin = fit.lwr_m, ymax = fit.upr_m), fill = "steelblue3", alpha = 0.35) +
  geom_point(color = "tomato2") +
  geom_point(aes(x = year, y = total_males), color = "steelblue3") + 
  geom_line(aes(x = year, y = fit.fit_f), color = "tomato2") +
  geom_line(aes(x = year, y = fit.fit_m), color = "steelblue3") +
  scale_x_continuous(limits = c(1965, 2018), expand=c(0,0)) +
  scale_y_continuous(limits = c(-100000, 2100000), expand=c(0,0)) +
  scale_colour_manual(name="Line Color",
    values=c(myline1="red", myline2="blue")) +
  labs(y = "Total graduate enrollment", x = "Year") +
  theme(legend.position = "top") +
  theme_classic()

ge_plot

ggsave(filename = "ge_plot.png", plot = ge_plot,
  scale = 1, width = 4.5, height = 3.375, units = "in",
  dpi = 600)
```


Problem 2 (Rachel):
```{r}
pf_fem <- pf %>% 
  filter(field == "physical_science" | field == "engineering" | field == "education" | field == "humanities", sex == "F") %>%
  select(field, year, number) %>%
  spread(year, number) %>%
  select(-field)

#p-value < 0.05, there is a significant effect of year on number of female students in each field 

rownames(pf_fem) <- c("physical_science", "engineering", "education", "humanities")

pf_chisqfem <- chisq.test(pf_fem)
pf_chisqfem
 
phd_shifts <- pf_fem %>% 
  ggplot(aes(x = year, y = number)) +
  geom_col(aes(fill = field), position = "dodge") +
  scale_x_continuous(expand=c(0,0), breaks = seq(1985,2015, by=15)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_classic() +
  labs(
    x = "Year",
    y = "Female PhDs Awarded"
  )
phd_shifts

#chi-square (need to work on)
#phd_chi <- chisq.test(pf_fem) 
#phd_chi
```

Problem 2 (Michael):
```{r}
pf_f <- pf %>% 
  filter(field == "physical_science" | field == "engineering" | field == "education" | field == "humanities", sex == "F") %>%
  select(field, year, number) %>%
  spread(year, number) %>%
  select(-field)

rownames(pf_f) <- c("physical_science", "engineering", "education", "humanities")

pf_chisqf <- chisq.test(pf_f)
pf_chisqf

pf_fplt <- pf %>% 
  filter(field == "physical_science" | field == "engineering" | field == "education" | field == "humanities", sex == "F") %>%
  select(field, year, number)
pf_fplt$year <- as.character(pf_fplt$year)

pf_plt <- ggplot(pf_fplt, aes(x = field, y = number)) +
  geom_col(aes(fill = year), position = "dodge", colour = "black") +
  theme_classic() +
  theme(legend.position = "top") +
  labs(
    x = "Field",
    y = "PhDs awarded to females"
  ) +
  scale_y_continuous(expand=c(0,0)) +
  scale_x_discrete(labels = c("education","engineering","humanities","physical science")) +
  scale_fill_brewer(palette = "Greys")
pf_plt

ggsave(filename = "pf_plt.png", plot = pf_plt,
  scale = 1, width = 7, height = 3, units = "in",
  dpi = 300)
```


Problem 3 (Rachel):
```{r}
melt_ms <- melt(ms)

#absolute difference in medians
#Employed Male/Female
emp_m_median <- median(ms$employment_male) #75167
emp_f_median <- median(ms$employment_female) #71750
emp_m_median - emp_f_median #3417
#Postdoc Male/Female
post_m_median <- median(ms$postdoc_male) #4800
post_f_median <- median(ms$postdoc_female) #4500
post_m_median - post_f_median # 3000

hist_emp_m = ggplot(ms, aes(ms$employment_male)) + geom_histogram()
qq_emp_m = ggplot(ms, aes(sample = ms$employment_male)) + geom_qq()

hist_emp_f = ggplot(ms, aes(ms$employment_female)) + geom_histogram()
qq_emp_f = ggplot(ms, aes(sample = ms$employment_female)) + geom_qq()

hist_post_m = ggplot(ms, aes(ms$postdoc_male)) + geom_histogram()
qq_post_m = ggplot(ms, aes(sample = ms$postdoc_male)) + geom_qq()

hist_post_f = ggplot(ms, aes(ms$postdoc_female)) + geom_histogram()
qq_post_f = ggplot(ms, aes(sample = ms$postdoc_female)) + geom_qq()

ftest_emp = var.test(ms$employment_male,ms$employment_female) # p=.88 thus variances are equal
ftest_post = var.test(ms$postdoc_male,ms$postdoc_female) # p=.85 thus variances are equal

#Mann-Whitney U
mwu_emp = wilcox.test(ms$employment_male,ms$employment_female)
mwu_emp # p = 0.3289 (not significant, ranks are equal)

mwu_post = wilcox.test(ms$postdoc_male,ms$postdoc_female)
mwu_post # p = 0.8671 (not significant, ranks are equal)

effsize_emp = cohen.d(ms$employment_male,ms$employment_female) # d estimate = 0.26 (small)
effsize_post = cohen.d(ms$postdoc_male,ms$postdoc_female) # d estimate = 0.04 (negligible)

#even though absolute difference is not significant, males are still paid a higher salary than females

ms_emp <- ms %>% 
  select(field_of_study, employment_male, employment_female) %>% 
  rename(Male = employment_male, Female = employment_female) %>% 
  gather(key = sex, value = employment, 2:3)

ms_post <- ms %>% 
  select(field_of_study, employment_male, employment_female) %>% 
  rename(Male = employment_male, Female = employment_female) %>% 
  gather(key = sex, value = postdoc, 2:3)

ms_joined <- merge(ms_emp, ms_post, by = c('field_of_study', 'sex'))


View (ms_joined)

gender <- c("Female", "Male")
sex_color <- c("white", "gray60")

emp_med_plot <- ggplot(fs_joined, aes(x = sex, y = employment)) +
  geom_boxplot(aes(fill = sex)) +
  scale_fill_manual(values = sex_color) +
  theme_classic() +
  scale_x_discrete(labels = gender) +
  labs(x = "Sex", y = "Median Employed Doctoral Recipient Salary (dollars) (n = 30)") +
  theme(plot.title = element_text(hjust = 0.5))

emp_med_plot


post_med_plot <- ggplot(ms_joined, aes(x = sex, y = employment)) +
  geom_boxplot(aes(fill = sex)) +
  scale_fill_manual(values = sex_color) +
  theme_classic() +
  scale_x_discrete(labels = gender) +
  labs(x = "Sex", y = "Median Doctoral Recipient Starting Salary (dollars) (n = 30)") +
  theme(plot.title = element_text(hjust = 0.5))

post_med_plot

ms_plot <- ggplot(melt_ms, aes(x = variable, y = value)) +
  geom_boxplot() +
  labs(y = "Median Doctoral Recipient Starting Salary (dollars)", x = "") + 
  scale_color_manual(values = c("white", "gray60", "white", "gray60"),
  labels=c("Employed Males","Employed Females","Male Postdocs","Female Postdocs"), name = "Employment") +
  scale_x_discrete(labels=c("Employed Males","Employed Females","Male Postdocs","Female Postdocs")) +
  theme_classic()

ms_plot

```
Problem 3 (Jeremy):
```{r}
ms_long <- melt(ms, variable.name = "status", value.name = "salary") 

ms_new <- ms_long %>% 
    #mutate(sdp = case_when(smoke==0 ~ "nonsmoker", #case_when() if smoke = 1 then replace with "smoker" smoke==1 ~ "smoker")
  mutate(sex = case_when(status == "employment_male" ~ "M",
                         status == "postdoc_male" ~ "M",
                         status == "employment_female" ~ "F",
                         status == "postdoc_female" ~ "F")) %>% 
  mutate(status = case_when(status == "employment_male" ~ "employed",
                         status == "postdoc_male" ~ "postdoc",
                         status == "employment_female" ~ "employed",
                         status == "postdoc_female" ~ "postdoc"))

male_postdoc <- ms_new %>% 
  filter(sex == "M", status == "postdoc") 
female_postdoc <- ms_new %>% 
  filter(sex == "F", status == "postdoc")
male_employed <- ms_new %>% 
  filter(sex == "M", status == "employed")
female_employed <- ms_new %>% 
  filter(sex == "F", status == "employed")

postdoc_u <- wilcox.test(male_postdoc$salary, female_postdoc$salary) # p = 0.87
# Median salary does not significantly differ between males and females starting postdoc positions in 2015.
employed_u <- wilcox.test(male_employed$salary, female_employed$salary) # p = 0.33
# Median salary does not significantly differ between males and females PhD recipients in non-postdoc employment positions.

postdoc_d <- cohen.d(male_postdoc$salary, female_postdoc$salary) # negligible
abs_postdoc <- median(male_postdoc$salary) - median(female_postdoc$salary) # males > females by $3000
perc_postdoc <- (median(male_postdoc$salary) - median(female_postdoc$salary))/(median(female_postdoc$salary)) * 100 # male postdoc salary 6.7% higher than females
employed_d <- cohen.d(male_employed$salary, female_employed$salary) # small
abs_employed <- median(male_employed$salary) - median(female_employed$salary) # males > females by $3417
perc_employed <- (median(male_employed$salary) - median(female_employed$salary))/(median(female_employed$salary)) * 100  # male employed salary 4.8% higher than females
```


Problem 4 (Rachel):
```{r}
# correlation of years since phd and years faculty service
yrs_corr <- fs %>% 
  ggplot(aes(x = years_since_PhD, y = years_faculty_service)) +
  geom_point(aes(color = sex), alpha = 0.5)
yrs_corr
#correlation years faculty service vs salary
service_corr <- fs %>% 
  ggplot(aes(x = years_faculty_service, y = salary)) +
  geom_point(aes(color = sex), alpha = 0.5)
service_corr

#filter by discipline -- should we run models for each discipline?
theoretical <- fs %>% 
  filter(discipline == "A")

applied <- fs %>% 
  filter(discipline == "B")

# Rank: reference level = profesor
fs$faculty_rank <- factor(fs$faculty_rank)
fs$faculty_rank <- fct_relevel(fs$faculty_rank, "Prof")
# everything model 
salary_lm1 <- lm(salary ~ faculty_rank + years_since_PhD + years_faculty_service + sex + discipline, data = fs)
plot(salary_lm1)
vif(salary_lm1)
# years since PhD = 7.5
# years faculty service = 5.9
# others less than 4
# years since phd and years faculty service is a bit redundant so maybe we don't need both?
salary_lm2 <- lm(salary ~ faculty_rank + years_faculty_service + sex + discipline, data = fs)
plot(salary_lm2)
vif(salary_lm2)
#faculty rank, discipline, sex, years_since_PhD
salary_lm3 <- lm(salary ~ faculty_rank + discipline + sex + years_since_PhD, data = fs)
plot(salary_lm3)
vif(salary_lm3)
#sex, rank discipline
salary_lm4 <- lm(salary ~ faculty_rank + discipline + sex, data = fs)
plot(salary_lm4)
vif(salary_lm4)
#rank, discipline, years_since_PhD
salary_lm5 <- lm(salary ~ faculty_rank + discipline + years_since_PhD, data = fs)
plot(salary_lm5)
vif(salary_lm5)

#AIC on all models
AIC(salary_lm1) #9094
AIC(salary_lm2) #9097
#lm1 has a lower AIC, but need to use judgmement do decide (look more into papers, think about whether service and years since phd are both needed)
AIC(salary_lm3) #9097
AIC(salary_lm4) #9095
AIC(salary_lm5) #9096

lm_table <- stargazer(salary_lm2, type = "html", title = "Faculty Salary Linear Model", digits = 2, align = TRUE, dep.var.labels = "Salary", covariate.labels = c("Associate Professor", "Assistant Professor", "Years Faculty Service", "Sex", "Discipline", "Constant"), out="model.htm")
lm_table
```

Problem 4 (Michael):
```{r}

fs_numonly <- fs %>%
  select(years_since_PhD, years_faculty_service, salary)
cor(fs_numonly)

# relevel faculty_rank to assistant prof
fs$faculty_rank <- factor(fs$faculty_rank)
fs$faculty_rank <- fct_relevel(fs$faculty_rank, "AsstProf")


# models
predsalary1 <- lm(salary ~ faculty_rank + discipline + years_since_PhD + years_faculty_service + sex, data = fs)
plot(predsalary1, which=c(2,1))

# the residuals do not look homoskedastic to me. this will effect predictive capacity, but not necessarily coefficients. 

fs_a <- fs %>%
  filter(discipline == "A") 
fs_b <- fs %>%
  filter(discipline == "B")

predsalary_a <- lm(salary ~ faculty_rank + years_since_PhD + years_faculty_service + sex, data = fs_a) # only theoretical
plot(predsalary_a, which=c(2,1))
AIC(predsalary_a)

predsalary_b <- lm(salary ~ faculty_rank + years_since_PhD + years_faculty_service + sex, data = fs_b) # only applied
plot(predsalary_b, which=c(2,1))
AIC(predsalary_b)

# heteroskedasticity seems to come mostly from applied faculty. Have two different models? 
# now take years since phd out

predsalary_a_simp1 <- lm(salary ~ faculty_rank + years_faculty_service + sex, data = fs_a) # only theoretical
plot(predsalary_a_simp1, which=c(2,1))
AIC(predsalary_a_simp1)

predsalary_b_simp1 <- lm(salary ~ faculty_rank + years_faculty_service + sex, data = fs_b) # only applied
plot(predsalary_b_simp1, which=c(2,1))
AIC(predsalary_b_simp1)


# AIC is larger for theoretical, only slightly smaller for applied.
# I think it is best to run different models for applied and theoretical, as their variances are different and they respond differently to years_since_phd and years_faculty_service
```

Problem 4 (Jeremy):
```{r}
lm_basic = lm(salary ~ discipline + faculty_rank + years_faculty_service + years_since_PhD + sex ,data = fs)
vif(lm_basic) # correlation between years variables 

lm2 = lm(salary ~ discipline + faculty_rank + years_since_PhD + sex ,data = fs)
vif(lm2)
plot(lm2)
summary(lm2)


fs_female = fs %>% 
  filter(sex == "Female")
fs_male = fs %>% 
  filter(sex == "Male")

fs_test = subset(fs, years_since_PhD < 40 | years_faculty_service < 36)

#EXPLORING INTERACTIONS:
explore_years_since_PhD = ggplot(data = fs_test, aes(x=years_since_PhD, y=salary, color=sex), alpha=.1) +
  geom_point(shape=1) +
    stat_smooth(aes(group = sex), method = "lm", formula = y ~ x, se = FALSE)

explore_years_faculty_service = ggplot(data = fs_test, aes(x=years_faculty_service, y=salary, color=sex), alpha=.1) +
  geom_point(shape=1) +
    stat_smooth(aes(group = sex), method = "lm", formula = y ~ x, se = FALSE)

explore_discipline = ggplot(data = fs_test, aes(x=discipline, y=salary, color=sex), alpha=.1) +
  geom_point(shape=1) +
    stat_smooth(aes(group = sex), method = "lm", formula = y ~ x, se = FALSE)

```








